# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mac-PropertyList-SAX
version:      0.03
version_from: lib/Mac/PropertyList/SAX.pm
installdirs:  site
requires:
    Carp:                          0
    enum:                          0
    Exporter:                      0
    Mac::PropertyList:             0
    MIME::Base64:                  0
    Test::More:                    0
    Text::Trim:                    0
    XML::SAX::Base:                0
    XML::SAX::ParserFactory:       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
