--- #YAML:1.0
name:                Mac-PropertyList-SAX
version:             0.06
abstract:            work with Mac plists at a low level (with real XML
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Carp:                          0
    enum:                          0
    Exporter:                      0
    Mac::PropertyList:             0
    MIME::Base64:                  0
    Test::More:                    0
    Text::Trim:                    0
    XML::SAX::Base:                0
    XML::SAX::ParserFactory:       0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Darren M. Kulp <darren@kulp.ch>
